import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SessionProvider from "@component/providers/session-provider";
import { LayoutProps } from "@lib/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        sdfg
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
