import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "../globals.css";
import SessionProvider from "@component/providers/session-provider";
import { LayoutProps } from "@lib/data";
import Header from "@component/header";
import AntDesignConfigProvider from "@component/providers/ant-design-config-provider";

const dmSans = DM_Sans({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700", "800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
    
export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <AntdRegistry>
          <AntDesignConfigProvider>
            <SessionProvider>
              <Header />
              {children}
            </SessionProvider>
          </AntDesignConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
